### ISSUE TITLE
[Question] Controlling knob using mouse and keyboard

### ISSUE THREAD

**Issue by Nedgeva** [satelllte/react-knob-headless#40]
Hi there! Thx for implementing interesting idea.
I opened demo page and tried to control knob using mouse and kb and I noticed following things:
1. knob primarily controls using Y-axis gesture. Personally I would expect it to be controllable using horizontal movement (e.g. left to decrease value and right to increase);
2. looks like it doesn't play well with kb's arrow keys as well as PgUp/PgDown.

So the question "Is this behavior intended"?

**Comment by satelllte** [comment]
Hi @Nedgeva 
Glad to see you here 👋🏻 

Short answer: **at this point**, yes & yes.

Let me explain ...

(1) I started with a bare minimum, so only vertical gesture is provided at this point. Why? I created this library for my own purposes first place once I found this reusable pattern. The main inspiration for this knob is the software like Ableton, Logic Pro, Native Instruments plugins, etc. They all implement the same kind of vertical gesture and it feels like it's the most common one in audio industry in general. If you want this knob to be extended to accept `horizontal` direction of the gesture, I'd be happy to patch it, just let me know.

Also, in the future, I might actually decouple the gesture somehow, or make it extendable, but I don't feel like there's a real need in it (at least, for now).

(2) Yes, it doesn't provide keyboard support yet. Why? See the explanation in "Gothas" section of documentation site - https://react-knob-headless.vercel.app:

>  There is no keyboard interaction provided by default. This is intentional, as knob behaviours might differ significantly between use cases. To achieve keyboard interaction, you can just provide your own "onKeyDown" listener.

So, as said, you can easily provide your own `onKeyDown` listener and update your value for some "step" and "smaller step" values (to follow ARIA Slider pattern).

Also, I'm currently working on a refactor for one of my apps, so I'm actually thinking to introduce a hook for keyboard support in more generic way than just follow ARIA, something similar to this:

```ts
export function useKnobKeyboard(options: {
  valueStep: number;
  valueStepSmall: number;
  keysStep: KeyPair[];
  keysStepSmall: KeyPair[];
  onValueRawChange: (newValueRaw: number) => void;
}) => ReactDOMAttributes
```

So if you have any ideas, suggestions, welcome 🙏

**Comment by satelllte** [comment]
Hi again @Nedgeva 👋🏻 

Horizontal orientation support is released 🎛️ 

Details:
- https://github.com/satelllte/react-knob-headless/releases/tag/v0.2.0
- https://react-knob-headless.vercel.app/

**Comment by satelllte** [comment]
Hi @Nedgeva 👋🏻 

Keyboard support added ⌨️

New hook: `useKnobKeyboardControls`
Documentation: https://react-knob-headless.vercel.app/
Release notes: https://github.com/satelllte/react-knob-headless/releases/tag/v0.3.0
