### ISSUE TITLE
Support for discrete values

### ISSUE THREAD

**Issue by tamlyn** [satelllte/react-knob-headless#56]
This component works great for continuous values like time and frequency, but not so good for discrete values like "number of steps" from 1 to 10. 

The problem is that I can't get it to snap to the values. 

https://github.com/satelllte/react-knob-headless/assets/115310/a7e7d065-8eb0-4f31-ba95-93960fd9e1a5

The `value` prop has to be continuous in order for the knob to rotate. If I round the `value` then the knob cannot move. Do you have any thoughts on how to achieve this? I'm thinking the component would probably have to hold some internal state for (rotation angle) and translate this to and from the external `value`.

**Comment by satelllte** [comment]
Hi @tamlyn! Thanks for trying out my library and opening the issue 🙏🏻 

The state is entirely in your control. For your use case you should just "lock" the rounded values visually.

If you take the docs example and round the value for the angle calculation, it'll do the desired snapping:

```ts
const angleMin = -145;
const angleMax = 145;
const angle = mapFrom01Linear(
  Math.round(value01 * 10) / 10,
  angleMin,
  angleMax,
);
```

so this should be a starting point, which you can adjust for your needs.

**Comment by tamlyn** [comment]
Yes! That works perfectly, thanks.
