### ISSUE TITLE
Unclear how to import

### ISSUE THREAD

**Issue by fourtrackFM** [satelllte/react-knob-headless#65]
After `npm install react-knob-headless`, it is unclear how to import KnobHeadless. typescript cannot find any module after install. Many other modules are used in this project. The usage is unclear in the docs. I really want to use this component because all the other react knobs are basically broken in one way or another. Making an accessible one is not trivial, and from the demo page this is the most usable.

Thank you for any clarification here.

**Comment by satelllte** [comment]
Hi. I see the source files are published correctly in the latest version of it: https://www.npmjs.com/package/react-knob-headless?activeTab=code. 

To begin using this library, you can import it this way:

```ts
import {KnobHeadless} from 'react-knob-headless';
```

---

I know the docs lack some simple examples now, but I hope I can bring them in the future.

For now, to get more sense of how this thing works, you can clone this repo, then run:

```
npm i
npm run dev
``` 

and then you can see how different knobs are made in `apps/docs`, which should give you a good start for designing your own.

**Comment by fourtrackFM** [comment]
Thanks for the quick reply, much appreciated!
